defaults: &defaults
  from_email: support@npocentral.com
  base_domain: npocentral.com

  gateway: bogus
  credentials:
    gateway:
      :login: demo
      :password: password
    paypal:
      :login: demo
      :password: password
      :signature: signature

development:
  <<: *defaults
  base_domain: npocentral.dev:3000 # Edit /etc/hosts to add subscriptions.dev, test.subscriptions.dev, etc., or use Pow: http://pow.cx

test:
  <<: *defaults

production:
  <<: *defaults
  credentials:
    gateway:
      :login: demo
      :password: password
    paypal:
      :login: demo
      :password: password
      :signature: signature